events {}

http {
  upstream frontend {
    server frontend:80;
  }

  upstream backend {
    server backend:3000;
  }

  server {
    listen 80;

    # Frontend
    location / {
      proxy_pass http://frontend;
    }

    # Backend API
    location /api/ {
      proxy_pass http://backend/;
    }
  }
}